import Head from "next/head";
import Footer from "./footer";
import Header from "./header";

const Layout = ({ props, children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>{children}</main>

      <Footer />
    </>
  );
};

export default Layout;
